[workspace]
members = [
    "crates/bankie-core",
    "crates/bankie-common",
    "crates/bankie-gateway",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
# Shared across crates
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
rust_decimal = "1.35.0"
rust_decimal_macros = "1.35.0"
chrono = { version = "^0.4.20", default-features = false, features = ["clock", "serde"] }
anyhow = "1"
uuid = { version = "1.10.0", features = ["v4", "fast-rng", "macro-diagnostics", "serde"] }
tracing = "0.1"
tracing-subscriber = "0.3"
axum = "0.7"
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5", features = ["compression-full", "cors", "validate-request", "add-extension", "trace"] }
jsonwebtoken = "9.3"
rand = "0.8"
sqlx = { version = "0.7.4", features = ["postgres", "runtime-tokio-rustls", "json", "uuid", "chrono", "rust_decimal"] }
redis = { version = "*", features = ["tokio-comp"] }
lazy_static = "1.5"
config = "0.14"
mockall = "0.10"
sha2 = "0.10"
hex = "0.4"
async-trait = "0.1"
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["client-legacy", "http1", "http2", "tokio"] }

# Internal crates
bankie-common = { path = "crates/bankie-common" }
