version: '3.9'

services:
  postgresql:
    container_name: postgresql
    image: docker.io/bitnami/postgresql:16
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_SHARED_BUFFERS=128MB
      - POSTGRESQL_WORK_MEM=32MB
      - POSTGRESQL_MAINTENANCE_WORK_MEM=64MB
      - POSTGRESQL_EFFECTIVE_CACHE_SIZE=512MB
      - POSTGRESQL_MAX_CONNECTIONS=100
      - POSTGRESQL_FSYNC=off
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      - default
  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - default
  bankie:
    container_name: bankie
    image: samwang0723/bankie:v0.1.0
    environment:
      - ENV=dev
      - DB_PASSWD=sample-password
      - JWT_SECRET=LPJkGKHgwJr9ts##xvX6cmWc96Wg(uVHDvNXwANsLXwL%pJnG4
      - RUST_LOG=info
      - SQLX_OFFLINE=true
    networks:
      - default
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
networks:
  default:
    driver: bridge
